### PR TITLE
Plot any language

### PR DESCRIPTION
**Pull request by dmnd**
Allows the user to plot any language, not just the top ten.

image

Caveat: I'm a MobX newbie. Advice welcome!

Test plan:

* Click the checkboxes in the first column of the table, then see the chart update.
* Click the pull request button and note the same languages stay selected.

### CODE REVIEW

**Comment by dmnd** [comment]
It appears that some tests are broken. It looks like previously both `<LangChart />` and `<LangTable />` knew how to filter to the top ten, but now only `<LangTable />` has that knowledge, so `<LangChart />` has an initial render with nothing selected.

Probably that logic should move to a store? Advice welcome for how to fix.

**Comment by madnight** [comment]
> Allows the user to plot any language, not just the top ten.

Hi dmbd, thx for your work, thats a very nice improvement. I'll have a look at your changeset this week.

**Comment by madnight** [comment]
What do you think about https://github.com/madnight/githut/compare/plot-any-lang?

image

**Comment by dmnd** [comment]
Works for me!

**Comment by dmnd** [comment]
Thanks, this is great.

**Pull request closed without merging**
