### PR TITLE
Save language visibility in localStorage

### PR DESCRIPTION
**Pull request by icholy**
I wanted to store them in url search parameters, but idk how to use react.

### CODE REVIEW

**Comment by icholy** [comment]
Changing the `visible` property on the `Series` object hides the label, it still gets drawn in the chart.

**Comment by madnight** [comment]
Could you explain in a few sentences what are you trying todo? Maybe I can implement that feature for you as url search parameter.

**Comment by icholy** [comment]
I have two issues. One is that I need to re-select the languages when cycling through the different views (issues, PRs, etc ...). The second is that there's no way to share a link with a set of pre-selected languages. For example:

https://madnight.github.io/githut/#/pushes/2020/4?l=javascript&l=python&l=ruby

I imagine it working like this:

* If there are url parameters, only selected those languages.
* If there are no url parameters, select the default languages.
* If a language is toggled, populate the url parameters with the current selection.

**Comment by madnight** [comment]
> I wanted to store them in url search parameters, but idk how to use react.

Hi @icholy,

I just implemented this feature for you. As you can see its a rather small patchset: https://github.com/madnight/githut/commit/aefc16147d544cd8d73087a51fda6110442a0827

Now, it's possible to preselect languages for comparison in the language chart by adding them to the URL like so:
https://madnight.github.io/githut/#/pull_requests/2021/1/Python,TypeScript,Shell,Lua

**Comment by icholy** [comment]
Awesome thanks!

**Pull request closed without merging**
