### PR TITLE
Add buttons, zip, and csv files to be downloaded

### LINKED ISSUE #57: Download Data
Add an option to be able to download data as csv

### PR DESCRIPTION
**Pull request by JeremyLARDENOIS**
Closes #57

### CODE REVIEW

**Comment by JeremyLARDENOIS** [comment]
Two ways to generate CSV and zip files. One by launching `convert_data.js` (work if .json are present), the other in query.js (not tested)
The downloading of zip file doesn't work. I don't know what URI I need to use.
I also didn't added data zipped and data in csv, but I can add them if you want.

**Comment by madnight** [comment]
Thanks for your effort. Would it be possible to generate csv and zip files on-the-fly when you press the download button without pushing it to the server (to put it in git)?

**Comment by JeremyLARDENOIS** [comment]
Maybe I didn't understand, but I think that generate a new zip file each time that someone click on "Download" is a bad idea if json files are not dynamic and uploaded manually. Instead, we can launch the convert_data.js script. If they are dynamic and loaded each time that someone connect on the website, I can generate zip and csv files on-the-fly.

**Comment by madnight** [comment]
The json files are currently not dynamic, but I can think of a future feature like download the json or csv only for a few selected languages. We already have the possibility to filter languages in the chart and to share a URL with pre-selected languages. So in this case it would be better to generate the csv and zip file on-the-fly, when a user hits the download button. Another reason is that I want to avoid to commit zip files into git. We already have a single source of truth, that's the json files, all other formats could be converted dynamically. This way it's also not possible to get inconsistent datasets (e.g. different values in csv vs json).

**Comment by JeremyLARDENOIS** [comment]
I understand the problem of consistency. Two choices are possible from my mind:
- Generate on the fly the file that asks the user for each file request
- Generate files one time by Github actions

**Comment by madnight** [comment]
If possible, e.g. it doesn't take too much time, then I would prefer to convert generate the csv and zip on-the-fly as soon as the user hits the download button. If it takes more than let's say 10 seconds to generate these files, then I would prefer GitHub actions.

**Comment by JeremyLARDENOIS** [comment]
I think it's ok to generate it on-the-fly so :smile: 
```sh
$ time node convert_data.js 
real	0m0,124s
user	0m0,121s
sys	0m0,026s
```

**Comment by JeremyLARDENOIS** [comment]
Just, what do I do if the file exists?

**Comment by madnight** [comment]
Could you elaborate?

**Comment by JeremyLARDENOIS** [comment]
Yes, I will try. I don't know if JSON files are sent to the client/navigator but if they aren't, that means that the conversion needs to be made on the server-side. If it is, the question is should I launch a generating or not if files CSV or zip are already generated? And if yes, how can I handle the fact that two users ask for files at the same time?

**Comment by madnight** [comment]
Isn't it possible to convert json to csv clientside only? So user hits the download button, fetch(json_url) -> store as blob -> convert to csv -> start download, something like this:

https://stackoverflow.com/a/63965930

**Comment by JeremyLARDENOIS** [comment]
It could be possible if JSON files were exposed. I don't know how to expose them.

**Comment by JeremyLARDENOIS** [comment]
@madnight Hi, I'm back ! (sorry for the delay) . I wanted to try to launch the project and i didn't achieve when I did the yarn install and npm run dev command, I caught an error, maybe due to node version, what is the node version that you support ?

**Comment by madnight** [comment]
Welcome back, 

I develop under Arch Linux which has quite recent node versions. Have you tried "yarn dev" instead of "npm run dev"? Can you provide the error message?

**Comment by madnight** [comment]
Node 16

**Comment by JeremyLARDENOIS** [comment]
Hello, I went to finished and rebase, I think that all is ready.
Let me know if there is something wrong, if you want to add something else or if you have any questions

**Comment by JeremyLARDENOIS** [comment]
@madnight still up ?

**Comment by JeremyLARDENOIS** [comment]
There is no problem. Was cool to contribute to this helpful project :)

**Pull request merged**
